title: Vincent's Deep Learning Blog
description: It's all about deep learning in medical imaging. 
show_downloads: true

baseurl: "/Vincent-DeepLearning-Blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://vincentycyao.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: 

# social
author: Vincent Y.C. Yao
image: 
twitter:
  username: VincentYCYao1
github: 
  username: VincentYCYao

plugins:
  - jekyll-target-blank
  - jekyll-seo-tag
  - jekyll-sitemap

target-blank:
    rel: nofollow

header_page_refs: ['Research','Linux', 'Python', 'Biography']
